// Tabela padrão de materiais elétricos para energia solar
// 48 materiais importados da planilha real da empresa
// Quantidades por potência de inversor

export const MATERIAIS_PADRAO = [
  { nome: 'BARRA ZINCADA 3/4"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1 } },
  { nome: 'BARRA ZINCADA 1"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 2, '8': 2, '10': 2, '4 MICRO': 2, '5 MICRO': 2, '6 MICRO': 2, '7 MICRO': 2, '8 MICRO': 2 } },
  { nome: 'CONDULETE TRAMON 3/4"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 6, '4': 6, '5': 6, '6': 6, '1 MICRO': 3, '2 MICRO': 3, '3 MICRO': 3 } },
  { nome: 'CONDULETE TRAMON 1"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 6, '8': 6, '10': 6, '4 MICRO': 4, '5 MICRO': 4, '6 MICRO': 4, '7 MICRO': 4, '8 MICRO': 4 } },
  { nome: 'CURVA ZINCADA 3/4"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2 } },
  { nome: 'CURVA ZINCADA 1"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 2, '8': 2, '10': 2, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'UNIDUT CONICO 3/4" TRAM.', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 12, '4': 12, '5': 12, '6': 12, '1 MICRO': 4, '2 MICRO': 4, '3 MICRO': 4 } },
  { nome: 'UNIDUT CONICO 1" TRAMON', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 12, '8': 12, '10': 12, '4 MICRO': 4, '5 MICRO': 4, '6 MICRO': 4, '7 MICRO': 4, '8 MICRO': 4 } },
  { nome: 'UNIDUT RETO EMENDA 3/4" TRAMONTINA', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 4, '4': 4, '5': 4, '6': 4 } },
  { nome: 'UNIDUT RETO EMENDA 1" TRAMONTINA', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 4, '8': 4, '10': 4, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'ARRUELA 3/4"', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '1 MICRO': 2, '2 MICRO': 2, '3 MICRO': 2 } },
  { nome: 'ARRUELA 1"', categoria: 'Fixação', unidade: 'unidade', quantidades: { '7.5': 1, '8': 1, '10': 1, '4 MICRO': 2, '5 MICRO': 2, '6 MICRO': 2, '7 MICRO': 2, '8 MICRO': 2 } },
  { nome: 'TAMPA CEGA TRAMONTINA 3/4"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 6, '4': 6, '5': 6, '6': 6, '1 MICRO': 3, '2 MICRO': 3, '3 MICRO': 3 } },
  { nome: 'TAMPA CEGA TRAMONTINA 1"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 6, '8': 6, '10': 6, '4 MICRO': 4, '5 MICRO': 4, '6 MICRO': 4, '7 MICRO': 4, '8 MICRO': 4 } },
  { nome: 'TAMPÃO PVC 3/4"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 15, '4': 15, '5': 15, '6': 15, '1 MICRO': 8, '2 MICRO': 8, '3 MICRO': 8 } },
  { nome: 'TAMPÃO PVC 1"', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '7.5': 15, '8': 15, '10': 15, '4 MICRO': 8, '5 MICRO': 8, '6 MICRO': 8, '7 MICRO': 8, '8 MICRO': 8 } },
  { nome: 'DISJUNTOR BIPOLAR 63', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'DISJUNTOR BIPOLAR 50', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '10': 1 } },
  { nome: 'DISJUNTOR BIPOLAR 40', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '7.5': 1, '8': 1 } },
  { nome: 'DISJUNTOR BIPOLAR 20', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '3': 1 } },
  { nome: 'DISJUNTOR BIPOLAR 25A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '4': 1 } },
  { nome: 'DISJUNTOR BIPOLAR 32', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '5': 1, '6': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1, '4 MICRO': 2, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'DISJUNTOR TRIPOLAR 63', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'DISJUNTOR TRIPOLAR 50', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR TRIPOLAR 40', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'HASTE DE ATERRAMENTO 1/2', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'CENTRINHO WEG 4 DIN', categoria: 'Proteção', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1 } },
  { nome: 'CENTRINHO WEG 6 DIN', categoria: 'Proteção', unidade: 'unidade', quantidades: { '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1 } },
  { nome: 'CENTRINHO WEG 12 DIN', categoria: 'Proteção', unidade: 'unidade', quantidades: { '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'GRAMPO PARA HASTE', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'DPS CLAMPER CA', categoria: 'DPS', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2, '1 MICRO': 2, '2 MICRO': 2, '3 MICRO': 2, '4 MICRO': 2, '5 MICRO': 2, '6 MICRO': 2, '7 MICRO': 3, '8 MICRO': 3 } },
  { nome: 'DPS CLAMPER CC', categoria: 'DPS', unidade: 'unidade', quantidades: {} },
  { nome: 'CHAVE SECCIONADORA 4 FIOS', categoria: 'Proteção', unidade: 'unidade', quantidades: {} },
  { nome: 'SPLITBOLT 16MM', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2, '1 MICRO': 2, '2 MICRO': 2, '3 MICRO': 2, '4 MICRO': 2, '5 MICRO': 2, '6 MICRO': 2, '7 MICRO': 2, '8 MICRO': 2 } },
  { nome: 'SPLITBOLT 10MM', categoria: 'Conexão', unidade: 'unidade', quantidades: {} },
  { nome: 'TERMINAL GENÉRICO', categoria: 'Conexão', unidade: 'unidade', quantidades: {} },
  { nome: 'TAMPA CEGA 1.1/2', categoria: 'Eletroduto', unidade: 'unidade', quantidades: {} },
  { nome: 'SELANTE PU QBORG', categoria: 'Outros', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1, '1 MICRO': 1, '2 MICRO': 1, '3 MICRO': 1, '4 MICRO': 1, '5 MICRO': 1, '6 MICRO': 1, '7 MICRO': 1, '8 MICRO': 1 } },
  { nome: 'CABO 6MM 1KV CORFIO', categoria: 'Cabo', unidade: 'metros', quantidades: {} },
  { nome: 'MANTA ASFALTICA', categoria: 'Outros', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR TRIPOLAR 32A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR BIPOLAR 25A (2)', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '4': 1 } },
  { nome: 'DISJUNTOR TRIPOLAR 70A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR BI 100A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR TRI 100A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'DISJUNTOR TRI 80A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: {} },
  { nome: 'ABRACADEIRA CUNHA 3/4', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 6, '4': 6, '5': 6, '6': 6 } },
  { nome: 'ABRACADEIRA CUNHA 1"', categoria: 'Fixação', unidade: 'unidade', quantidades: { '7.5': 6, '8': 6, '10': 6 } },
];

export const CABOS_PADRAO = [
  { potencia: '3', tipo_cabo: 'Cabo 4mm 1kV', observacao: 'Cabo CC' },
  { potencia: '3', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '4', tipo_cabo: 'Cabo 4mm 1kV', observacao: 'Cabo CC' },
  { potencia: '4', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '5', tipo_cabo: 'Cabo 6mm 1kV', observacao: 'Cabo CC' },
  { potencia: '5', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '6', tipo_cabo: 'Cabo 6mm 1kV', observacao: 'Cabo CC' },
  { potencia: '6', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '7.5', tipo_cabo: 'Cabo 10mm 1kV', observacao: 'Cabo CC' },
  { potencia: '7.5', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '8', tipo_cabo: 'Cabo 10mm 1kV', observacao: 'Cabo CC' },
  { potencia: '8', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '10', tipo_cabo: 'Cabo 16mm 1kV', observacao: 'Cabo CC' },
  { potencia: '10', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '1 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '1 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '2 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '2 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '3 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '3 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '4 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '4 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '5 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '5 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '6 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '6 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '7 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '7 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '8 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '8 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
];
