// Tabela padrão de materiais elétricos para energia solar
// Quantidades por potência de inversor

export const MATERIAIS_PADRAO = [
  { nome: 'BARRA ZINCADA 3/4', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 3, '6': 3, '7.5': 4, '8': 4, '10': 5 } },
  { nome: 'CURVA 3/4', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 4, '4': 4, '5': 6, '6': 6, '7.5': 8, '8': 8, '10': 10 } },
  { nome: 'ABRAÇADEIRA TIPO U 3/4', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 10, '4': 10, '5': 15, '6': 15, '7.5': 20, '8': 20, '10': 25 } },
  { nome: 'BUCHA 10 + PARAFUSO SEXTAVADO', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 10, '4': 10, '5': 15, '6': 15, '7.5': 20, '8': 20, '10': 25 } },
  { nome: 'CONECTOR MC4 MACHO', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'CONECTOR MC4 FÊMEA', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'DISJUNTOR BIPOLAR CC 25A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CC 32A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '7.5': 1, '8': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CC 40A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '10': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CA 25A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '3': 1, '4': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CA 32A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '5': 1, '6': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CA 40A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '7.5': 1, '8': 1 } },
  { nome: 'DISJUNTOR BIPOLAR CA 50A', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '10': 1 } },
  { nome: 'DPS CC 600V', categoria: 'DPS', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'DPS CA 275V', categoria: 'DPS', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'QUADRO STRG BOX 6 POSIÇÕES', categoria: 'Proteção', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1 } },
  { nome: 'PRENSA CABO PG 21', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 2, '4': 2, '5': 2, '6': 2, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'TERMINAL TUBULAR 4mm', categoria: 'Conexão', unidade: 'unidade', quantidades: { '3': 4, '4': 4, '5': 0, '6': 0 } },
  { nome: 'TERMINAL TUBULAR 6mm', categoria: 'Conexão', unidade: 'unidade', quantidades: { '5': 4, '6': 4 } },
  { nome: 'TERMINAL TUBULAR 10mm', categoria: 'Conexão', unidade: 'unidade', quantidades: { '7.5': 4, '8': 4 } },
  { nome: 'TERMINAL TUBULAR 16mm', categoria: 'Conexão', unidade: 'unidade', quantidades: { '10': 4 } },
  { nome: 'FITA ISOLANTE', categoria: 'Outros', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1 } },
  { nome: 'FITA AUTOFUSÃO', categoria: 'Outros', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 1, '8': 1, '10': 1 } },
  { nome: 'PRESILHA PLÁSTICA 200mm', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 20, '4': 20, '5': 30, '6': 30, '7.5': 40, '8': 40, '10': 50 } },
  { nome: 'CANALETA 20x10', categoria: 'Eletroduto', unidade: 'unidade', quantidades: { '3': 1, '4': 1, '5': 1, '6': 1, '7.5': 2, '8': 2, '10': 2 } },
  { nome: 'PARAFUSO FRANCÊS 5/16 x 2"', categoria: 'Fixação', unidade: 'unidade', quantidades: { '3': 4, '4': 4, '5': 4, '6': 4, '7.5': 6, '8': 6, '10': 8 } },
  { nome: 'DISJUNTOR BIPOLAR CA 20A (MICRO)', categoria: 'Disjuntor', unidade: 'unidade', quantidades: { '1 MICRO': 1, '2 MICRO': 2, '3 MICRO': 2, '4 MICRO': 2, '5 MICRO': 3, '6 MICRO': 3, '7 MICRO': 3, '8 MICRO': 4 } },
  { nome: 'CONECTOR WAP DERIVAÇÃO', categoria: 'Conexão', unidade: 'unidade', quantidades: { '1 MICRO': 2, '2 MICRO': 3, '3 MICRO': 4, '4 MICRO': 5, '5 MICRO': 6, '6 MICRO': 7, '7 MICRO': 8, '8 MICRO': 9 } },
];

export const CABOS_PADRAO = [
  { potencia: '3', tipo_cabo: 'Cabo 4mm 1kV', observacao: 'Cabo CC' },
  { potencia: '3', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '4', tipo_cabo: 'Cabo 4mm 1kV', observacao: 'Cabo CC' },
  { potencia: '4', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '5', tipo_cabo: 'Cabo 6mm 1kV', observacao: 'Cabo CC' },
  { potencia: '5', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '6', tipo_cabo: 'Cabo 6mm 1kV', observacao: 'Cabo CC' },
  { potencia: '6', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '7.5', tipo_cabo: 'Cabo 10mm 1kV', observacao: 'Cabo CC' },
  { potencia: '7.5', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '8', tipo_cabo: 'Cabo 10mm 1kV', observacao: 'Cabo CC' },
  { potencia: '8', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '10', tipo_cabo: 'Cabo 16mm 1kV', observacao: 'Cabo CC' },
  { potencia: '10', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '1 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '1 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '2 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '2 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '3 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '3 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '4 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '4 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '5 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '5 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '6 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '6 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '7 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '7 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
  { potencia: '8 MICRO', tipo_cabo: 'Cabo PP 3x6mm', observacao: 'Cabo CA microinversor' },
  { potencia: '8 MICRO', tipo_cabo: 'Cabo verde 4mm', observacao: 'Aterramento' },
];
